### ISSUE TITLE
老大哥帮帮忙，npm run init 和 npm run start 运行机器人行为不一致

### ISSUE THREAD

**Issue by Mark9804** [Mark9804/Adachi-BOT#35]
我merge之后，用`npm run init`运行bot可以正常发送`米游社`和`深渊`的图片，但是如果`npm run start`运行bot，查询`米游社`时就会返回`Error: Node has 0 height.` 仅仅启动方式不一样会有这种差别吗

node版本：       v17.0.1
OS信息：          macOS 12.0.1
本地代码状态：和GitHub同步

![image](https://user-images.githubusercontent.com/9006264/141612403-36661525-f7aa-45fd-85e4-59cc527e61f3.png)

@Arondight

**Comment by Mark9804** [comment]
感觉半破案了，我开前端调试模式跑，通过`npm run start`的话访问不到深渊和米游社的网页，但是`信息`是正常的；
`npm run init`倒是没有这个问题
![image](https://user-images.githubusercontent.com/9006264/141612740-ea3877ca-8f6f-4110-9a3f-4cba2c46f7fa.png)

**Comment by Arondight** [comment]
我忘了给 start 加上 --max-http-header-size 2097152 了

**Comment by Arondight** [comment]
加上了

**Comment by Mark9804** [comment]
感谢，我本来还想顺便给上游加上的，后来发现我不会，刚刚才查到要加json里面

**Comment by Arondight** [comment]
新版本上了开发板，没上生产版本，我觉得开发版对我们是好的，而这两个版本很明显对用户来说没有任何区别
